from pathlib import Path
import re
from xml.sax.saxutils import escape

en = {
'equation_heading': 'Design equation and code reference',
'pressure_equation_units': 'Pressure equations use MPa: input bar × 0.1 = MPa. D, R and wall dimensions are in mm; S is MPa. E/W/Y are unitless. Miter equations produce Pm in MPa; the screen converts it to bar.',
'weight_equation_units': 'D and t in mm, length L in m, density ρ in kg/m³. Output is kg/m and kg. Weight formulas are geometry calculations, not a B31 pressure-design check.',
'material_manual_stress_note': 'Room temperature starts at 20°C. Select the exact specification and grade, then enter S from the appropriate code table at your design metal temperature. This list does not certify material suitability.',
'stress_manual_source_note': 'No verified automatic S is available for this code/material/temperature. Enter it from the code table using the ? guidance; do not use yield or tensile strength.',
'stress_verified_source': 'Verified starting value: %1$s MPa, B31.1-2022 Table A-1 pp.126–127, A106 seamless, note (2), %2$d°F column (%3$s ksi). Uses the next listed “not exceeding” column; no interpolation/extrapolation. You may override it after checking the applicable notes.',
'use_verified_stress': 'Use verified table value',
'guide_stress_b313': 'S is allowable design stress, in MPa; it is not yield strength or tensile strength. Find the exact specification, grade and product form in B31.3-2018 Table A-1 (US units) or A-1M (SI), then the design metal temperature column. Read the row notes and temperature limits. Use MPa here: ksi × 6.894757293168 = MPa. No B31.3 stress table has been verified for automatic filling in this app; enter the project-approved value manually. Material or temperature changes clear the old S.',
'guide_stress_b311': 'S is entered in MPa before applying E/F. Use B31.1-2022 Mandatory Appendix A, Table A-1, the exact material/product row and design temperature column. The table can publish a combined SE/SF value: do not multiply an already reduced value by E twice. Automatic values are limited to verified A106 seamless rows (E=1), pp.126–127, 20°C through the supplied 800°F column. Other forms/temperatures remain manual. The app chooses the next printed “not exceeding” column and shows it; read note (2) and material limits before use. Example: 17.1 ksi = 117.90035 MPa.',
'guide_stress_vessel': 'S is allowable stress at the design metal temperature, in MPa, from the applicable edition of ASME BPVC Section II, Part D, Tables 1A (ferrous) or 1B (nonferrous), with the product form, specification, grade, thickness and notes required by VIII Division 1. Use the permitted row for this vessel service. Do not use B31.1/B31.3 stress values or room-temperature yield/tensile strength as a substitute. The app has no verified vessel stress lookup; enter the approved S manually.',
'guide_code': 'Choose the code in the project design basis or piping specification: B31.3-2018 for the implemented process-piping paths, B31.1-2022 for the implemented power-piping paths. They use different equations, material tables and limits. Do not choose whichever gives the smallest thickness. The bend tab currently implements B31.3; pressure vessels use BPVC VIII Division 1, not either piping code.',
'guide_b311_group': 'This group selects y only from B31.1-2022 Table 104.1.2-1. Determine the alloy family/UNS designation from the material certificate and table row. It does not supply S or establish material temperature suitability. Blank table cells are not valid values. Ferritic/austenitic steel at ≤482°C also uses note (b) when Do/tm < 6.',
'guide_miter_t': 'T is the wall of the actual miter segment, in mm, per B31.3-2018 304.2.3(d): measured wall or the guaranteed minimum allowed by the purchase specification. Obtain it from a certified thickness measurement, the manufacturer’s drawing/certificate, or the pipe schedule after checking the applicable minus tolerance. It is not the required thickness calculated as an output, not the pipe diameter and not automatically a nominal plate thickness. The pressure formulas use T−c; T must exceed c. Example: measured/minimum T=6.02 mm and c=1.5 mm leaves 4.52 mm for pressure.',
'guide_miter_c': 'c is a total metal allowance, in mm: corrosion + erosion + mechanical removal such as thread/groove depth. B31.3-2018 304.1.1(b) defines it, and 304.2.3(d) uses the same c for miters. Obtain corrosion/erosion from the approved piping specification/design life; obtain machining depth/tolerance from the fabrication drawing. Example: 1.5 + 0.5 + 1.0 = 3.0 mm. Do not add manufacturing minus tolerance to c or subtract it twice from a measured wall. Use 0 only when justified by the design. This c is not the empirical A in miter Eq. (5).',
'guide_miter_angle': 'Enter the total change of direction of the assembly, in degrees, from the isometric/fabrication drawing. The app divides it by the number of miter weld joints, then by 2 to get the code’s cut angle θ. Example: 90° across 2 joints means 45° per joint and θ=22.5°. Do not enter θ itself in this total-angle field. B31.3-2018 304.2.3/Fig.304.2.3 defines the angles.',
'guide_miter_joints': 'Count the miter weld joints where pipe direction changes, from the fabrication drawing; do not count the pipe pieces. Two pieces joined at one miter have 1 joint; three pieces have 2 joints. Equal division of the total angle is assumed. Unequal joint angles need separate assessment. This count determines single versus multiple miter equations in B31.3-2018 304.2.3.',
'guide_miter_b': 'B is the crotch/segment dimension defined for the actual miter geometry, in mm; obtain it from the approved fabrication drawing using ASME B31J terminology referenced by B31.1-2022 104.2.3. It is not the pipe OD or bend radius. The decision paths check B < 6tn, with tn the nominal segment wall. Do not estimate B from a photo or total bend angle.',
'guide_radius_b313': 'R1 is the effective miter radius in mm: the shortest distance from pipe centreline to the intersection of adjacent miter-joint planes, per B31.3-2018 304.2.3(d) and Fig.304.2.3. Obtain it from the dimensioned fabrication geometry, not the pipe radius or a standard elbow label. Eq. (5) requires R1 ≥ A/tanθ + D/2. The app calculates this minimum using T−c; empirical A is 25, 2(T−c), or 2(T−c)/3+30 in the printed SI ranges. Do not substitute corrosion allowance for A.',
'guide_radius_b311': 'R is the bend radius required by the close-miter segment equation in B31.1-2022 104.2.3(c)(3)(-a). Obtain R and pipe radius r from the approved drawing with the ASME B31J definitions referenced by that paragraph. The calculation requires R > r. Do not substitute the pipe OD for R or assume that the B31.3 effective-radius definition is identical.',
'guide_miter_spacing': 'Choose closely or widely spaced from the approved assembly geometry using ASME B31J, as required by B31.1-2022 104.2.3(c)(3). The app uses your declared classification; it does not infer it from number of pieces or angle alone. Close spacing uses the radius-ratio formula; wide spacing solves the printed implicit equation. This thickness check does not replace qualification under 104.7.',
'guide_miter_tm': 'tm is the minimum straight-pipe wall required by B31.1 para.104.1 for this same material, design pressure/temperature and allowances, in mm. Calculate it first in the straight-pipe tab with B31.1 selected, or use an approved design calculation. Copy tm including A, not pressure thickness t alone, and not the purchased nominal wall. This becomes the baseline for the segment thickness ts in 104.2.3(c)(3).',
'guide_miter_r': 'r is the pipe radius defined for this miter calculation by ASME B31J, referenced in B31.1-2022 104.2.3. Obtain it from the approved dimensioned geometry/pipe wall definition. Enter mm, not the diameter, and distinguish it from assembly bend radius R. The formulas contain r/R or sqrt(r/ts); using diameter instead of radius changes the result.',
'guide_e_b311': 'E (or F for cast material) is the quality factor for the actual product form, from B31.1-2022 Appendix A and 102.4.3. Identify seamless/ERW/furnace-welded/cast construction from the certificate. The supplied A106 seamless row has E=1; that does not justify 1 for every pipe. Table stress values may already be SE/SF. Enter unreduced S with E once; do not apply the factor twice.',
'guide_w_b311': 'W is the weld-strength reduction factor, unitless, per B31.1-2022 102.4.7. Determine applicability from material, weld type, design metal temperature and the prescribed table/notes. Use the certificate, approved design basis and the exact code edition. It is distinct from product quality E. Enter a value in (0,1]; use 1 only when justified, not because it gives a thinner wall.',
'guide_y_b311': 'y is the dimensionless coefficient from B31.1-2022 Table 104.1.2-1 for the selected material group and temperature. The app interpolates published y cells and applies note (b) for eligible steel at ≤482°C and Do/tm<6. It is not S and does not validate material temperature limits. Manual entry overrides the table; verify the source and notes before overriding.',
'guide_material_vessel': 'Use the ASME material specification and product form on the vessel material certificate, such as SA-516 plate rather than a pipe grade. The dropdown is identification only. Confirm material eligibility in VIII Division 1 and the applicable stress row/notes in Section II-D Tables 1A/1B at the design temperature. Enter the exact certificate designation under Other when needed.',
'guide_generic': 'Record the value or designation from the approved design/fabrication document for this item. Optional report names and references identify the calculation; they do not change its equations. If a required engineering value is unavailable, obtain it from the responsible designer rather than guessing.',
'help_material': 'Select the exact ASTM specification, grade and construction from the mill/material certificate (MTC). The dropdown identifies the material; it does not certify suitability. S depends on both code and metal temperature, E on construction, and W on weld/temperature rules. Use Other for a designation not listed and verify the code material table/notes.',
'help_material_name': 'Copy the specification, grade, product form and any relevant UNS designation from the material certificate or approved piping specification. Example: ASTM A106 Gr.B seamless pipe. A trade name or “carbon steel” alone is not enough to select a stress-table row.',
'help_temperature': 'Design metal temperature in °C, from the line list, equipment datasheet or approved design basis for the governing pressure/temperature case. The default 20°C is room temperature for starting the form, not an assumed operating/design condition. S must be rechecked at the new temperature; do not keep the room-temperature stress for a hot line. Material/temperature changes invalidate dependent coefficients.',
'help_od': 'Outside diameter D/Do, not NPS or inside diameter. Obtain it from B36.10/B36.19 dimensions for the specified product, its certified drawing, or an accepted measurement where the code permits. Exclude coatings. In an mm field enter mm; in a selectable-unit field use the selected unit. Example: NPS 4 has OD 114.3 mm, not 4 mm.',
'help_pressure': 'Internal design gauge pressure in bar(g), from the approved line list/P&ID/design datasheet. Gauge is relative to atmospheric pressure; absolute pressure must be converted appropriately. Do not enter a hydrotest pressure or operating reading unless it is the approved design case. Example: 20 bar(g) = 2 MPa; the app converts bar to MPa before the equation.',
'help_corrosion': 'Corrosion allowance in mm for metal expected to be lost during the design life. Obtain it from the project material/piping class, corrosion study or vessel specification. It is not measured wall loss on an old pipe. Example: a specified 1.5 mm allowance is entered as 1.5. Enter 0 only when the design basis justifies it.',
'help_erosion': 'Additional erosion allowance in mm, from the approved design/corrosion-erosion assessment for the fluid and velocity/particles. Do not repeat an erosion amount already included in the project corrosion allowance. Enter 0 only when no separate erosion allowance is required by the design.',
'mechanical_allowance_hint': 'Metal removed by threading, grooving or machining, in mm, from the fabrication drawing and tolerance. B31.3-2018 304.1.1(b) requires thread/groove depth; when groove/machining tolerance is unspecified, add 0.5 mm to the specified cut depth. For B31.1 review 102.4.2 and mechanical-strength allowances in 102.4.4. This allowance belongs in pre-machining wall; do not deduct already removed metal again from a finished measurement.',
'mill_tolerance_hint': 'Manufacturer’s permitted minus wall tolerance, in percent, from the exact product/purchase specification and certificate (e.g. the applicable ASTM/ASME pipe specification). Do not assume 12.5% for every product. Nominal ordering wall = required minimum/(1−tol/100). This is a purchase check, not a deduction from a certified measured minimum wall.',
'help_e': 'Quality factor E, unitless, from B31.3-2018 Table A-1A/A-1B and 302.3.3/302.3.4 notes for the actual product and weld examination. Read the MTC to identify seamless or welded construction, then the applicable table row. 1 may apply to suitable seamless product, but is not universal. Use S from A-1/A-1M separately and enter E only once; E is not W or yield strength.',
'help_w': 'W is the weld-joint strength reduction factor at the design metal temperature, from B31.3-2018 302.3.5(e) and Table 302.3.5 (including steel group, heat treatment and notes). Use the material/weld certificates and approved design basis. It is unitless and distinct from E. A starting value of 1 must be confirmed for the actual material/weld and temperature; do not reuse a cold-service value at high temperature without checking.',
'help_y': 'Y is the dimensionless coefficient from B31.3-2018 Table 304.1.1, selected by material class and temperature, not allowable stress. For ferritic steel the printed transition is 0.4/0.5/0.7 at 482/510/538°C; austenitic steel transitions at 566/593/621°C. Automatic values use the table/interpolation where available. You may override the shown value after checking the row and notes. The simple pipe equation still requires t<D/6 and P/(SE)≤0.385.',
'help_bend_radius': 'R1 is the centreline bend radius in mm, from the elbow manufacturer’s dimensioned drawing or pipe-bend fabrication drawing; not the pipe cross-section radius. B31.3-2018 304.2.1 uses R1/D in I. Standard “long radius 1.5D” usually uses nominal pipe size for its dimensional designation; do not automatically multiply actual OD by 1.5. Enter the certified centreline radius (e.g. NPS 4 LR commonly approximately 152 mm), and ensure R1>D/2.',
'help_joint_efficiency': 'Vessel joint efficiency E, unitless, from ASME VIII Division 1 Table UW-12 and applicable UW-11 examination requirements. Use the vessel weld map, joint category/type and radiography/other examination records. Do not use a piping quality-factor table here. A default 1 requires the applicable row/examination to justify it; obtain the approved efficiency from the vessel designer.',
'help_nominal_vessel_thickness': 'Nominal component plate/wall thickness in mm, from the vessel drawing or plate certificate, for the MAWP check. The app uses thickness minus corrosion allowance and applies the implemented component limits. It does not predict forming thinning or qualify all vessel loads. Do not enter a pressure-design output as if it were measured or purchased wall.',
}
ar = {
'equation_heading': 'المعادلة ومرجع الكود',
'pressure_equation_units': 'معادلات الضغط تستخدم MPa: قيمة الضغط بالبار × 0.1 = MPa. الأقطار وأنصاف الأقطار والسماكات بالملليمتر، وS بوحدة MPa؛ المعاملات E/W/Y بلا وحدة. معادلات المايل تنتج Pm بوحدة MPa وتحوله الشاشة إلى بار.',
'weight_equation_units': 'D وt بالملليمتر، والطول L بالمتر، والكثافة ρ بوحدة كجم/م³. النتيجة كجم/م وكجم. هذه معادلات هندسة وكتلة وليست فحص ضغط وفق B31.',
'material_manual_stress_note': 'تبدأ الحرارة عند 20°م (حرارة الغرفة). اختر المواصفة والدرجة بدقة، ثم أدخل S من جدول الكود المناسب عند حرارة معدن التصميم. القائمة لا تثبت صلاحية المادة للخدمة.',
'stress_manual_source_note': 'لا تتوفر قيمة S تلقائية موثقة لهذا الكود والمادة والحرارة. أدخلها من جدول الكود وفق شرح علامة ؟؛ لا تستخدم إجهاد الخضوع أو مقاومة الشد بدلًا منها.',
'stress_verified_source': 'قيمة بدء موثقة: %1$s MPa، من B31.1-2022 جدول A-1 ص126–127، صف A106 بدون لحام، الملاحظة (2)، عمود %2$d°F (%3$s ksi). يُستخدم العمود المطبوع التالي الذي لا تتجاوز حرارته، دون استيفاء أو استقراء. يمكنك تعديل القيمة بعد مراجعة الملاحظات المنطبقة.',
'use_verified_stress': 'استخدام قيمة الجدول الموثقة',
'guide_stress_b313': 'S هو إجهاد التصميم المسموح بوحدة MPa، وليس إجهاد الخضوع أو مقاومة الشد. ابحث عن المواصفة والدرجة وشكل المنتج في B31.3-2018 جدول A-1 للوحدات الأمريكية أو A-1M للوحدات المترية، ثم عمود حرارة معدن التصميم. راجع ملاحظات الصف وحدود الحرارة. للتحويل: ksi × 6.894757293168 = MPa. لم يُتحقق هنا من جدول إجهاد B31.3 للتعبئة التلقائية؛ أدخل القيمة المعتمدة يدويًا. تغيير المادة أو الحرارة يمسح S القديمة.',
'guide_stress_b311': 'أدخل S بوحدة MPa قبل تطبيق E/F. المرجع: B31.1-2022 الملحق الإلزامي A، جدول A-1، صف المادة وشكل المنتج وعمود حرارة التصميم. قد تكون قيمة الجدول مركبة SE/SF؛ لا تضرب قيمة مخفضة أصلًا في E مرة ثانية. التعبئة التلقائية محدودة بصفوف A106 بدون لحام الموثقة (E=1)، ص126–127، من 20°م حتى عمود 800°F المرفق. ما عدا ذلك يدوي. التطبيق يختار العمود التالي المطبوع بصيغة «لا تتجاوز» ويذكره؛ راجع الملاحظة (2) وحدود المادة. مثال: 17.1 ksi = 117.90035 MPa.',
'guide_stress_vessel': 'S هو الإجهاد المسموح عند حرارة معدن التصميم بوحدة MPa، من إصدار ASME BPVC Section II Part D المنطبق: جدول 1A للمواد الحديدية أو 1B لغير الحديدية، مع مطابقة المواصفة والدرجة وشكل المنتج والسمك والملاحظات المطلوبة للأوعية VIII Division 1. لا تستبدله بقيم B31.1/B31.3 أو بإجهاد الخضوع والشد عند حرارة الغرفة. لا يتوفر جدول إجهاد أوعية موثق تلقائيًا هنا؛ أدخل القيمة المعتمدة يدويًا.',
'guide_code': 'اختر الكود من أساس تصميم المشروع أو مواصفة الأنابيب: B31.3-2018 للمسارات الصناعية المنفذة، أو B31.1-2022 لمسارات أنابيب القدرة المنفذة. تختلف المعادلات وجداول المواد والحدود؛ لا تختَر الكود الذي يعطي أقل سمك. تبويب الأكواع الحالي يطبق B31.3، والأوعية تستخدم BPVC VIII Division 1 وليس أيًا من كودي الأنابيب.',
'guide_b311_group': 'تختار هذه المجموعة معامل y فقط من B31.1-2022 جدول 104.1.2-1. حدد عائلة السبيكة أو رقم UNS من شهادة المادة وصف الجدول. لا تعطي S ولا تثبت صلاحية المادة للحرارة. الخلايا الفارغة ليست قيمًا مسموحة. للفولاذ الفيريتي والأوستنيتي حتى 482°م تُطبّق الملاحظة (b) أيضًا عندما Do/tm < 6.',
'guide_miter_t': 'T هو جدار قطعة الانحناء المايل الفعلية بالملليمتر، وفق B31.3-2018 الفقرة 304.2.3(d): سمك مقاس أو أقل سمك مضمون بمواصفة الشراء. خذه من قياس سمك معتمد، أو رسم وشهادة المصنع، أو جدول الماسورة بعد مراجعة تفاوت النقص المنطبق. ليس السمك المطلوب الذي تظهره الحاسبة كخرج، وليس القطر، وليس تلقائيًا سمك لوح اسمي. تستخدم معادلة الضغط T−c، لذلك يجب أن يزيد T على c. مثال: T=6.02 مم وc=1.5 مم يتركان 4.52 مم لمقاومة الضغط.',
'guide_miter_c': 'c هو إجمالي سماحيات المعدن بالملليمتر: التآكل + النحر + المعدن المزال بالقلاوظ أو المجاري أو التشغيل. تعريفه في B31.3-2018 الفقرة 304.1.1(b)، وتستخدمه 304.2.3(d) للمايل. خذ التآكل والنحر من مواصفة المشروع وعمر التصميم، وعمق التشغيل وتفاوته من رسم التصنيع. مثال: 1.5 + 0.5 + 1.0 = 3.0 مم. لا تضف تفاوت المصنع إلى c ولا تخصمه مرتين من سمك مقاس. أدخل صفرًا فقط إذا برره التصميم. هذا c ليس A التجريبي في معادلة المايل (5).',
'guide_miter_angle': 'أدخل مجموع تغير اتجاه التجميعة بالدرجات من الأيزومتريك أو رسم التصنيع. يقسمه التطبيق على عدد وصلات اللحام المايلة ثم على 2 ليحسب زاوية القطع θ. مثال: 90° على وصلتين = 45° لكل وصلة وθ=22.5°. لا تدخل θ نفسها في حقل الزاوية الكلية. المرجع: B31.3-2018 الفقرة 304.2.3 والشكل 304.2.3.',
'guide_miter_joints': 'عُد وصلات اللحام المايلة التي يتغير عندها اتجاه الماسورة، وليس عدد قطع الماسورة. قطعتان متصلتان عند قطع مايل = وصلة واحدة؛ ثلاث قطع = وصلتان. خذ العدد من رسم التصنيع. يفترض التطبيق توزيع الزاوية بالتساوي؛ الزوايا غير المتساوية تحتاج تقييمًا منفصلًا. العدد يحدد مسار المفرد والمتعدد في B31.3-2018 الفقرة 304.2.3.',
'guide_miter_b': 'B هو بُعد منطقة التقاء/قطعة المايل حسب تعريف الهندسة الفعلية، بالملليمتر. خذه من رسم التصنيع المعتمد بتعريفات ASME B31J التي تحيل إليها B31.1-2022 الفقرة 104.2.3. ليس القطر الخارجي ولا نصف قطر الانحناء. تقارن المسارات B مع 6tn، حيث tn السمك الاسمي للقطعة. لا تستنتجه من صورة أو من زاوية الانحناء وحدها.',
'guide_radius_b313': 'R1 هو نصف قطر المايل الفعّال بالملليمتر: أقصر مسافة من خط مركز الماسورة إلى تقاطع مستويَي وصلتين مايلتين متجاورتين، حسب B31.3-2018 الفقرة 304.2.3(d) والشكل 304.2.3. خذه من الرسم الهندسي ذي الأبعاد، وليس نصف قطر مقطع الماسورة أو اسم كوع قياسي. تشترط المعادلة (5): R1 ≥ A/tanθ + D/2. يحسب التطبيق الحد من T−c؛ قيم A التجريبية هي 25 أو 2(T−c) أو 2(T−c)/3+30 في النطاقات المترية المطبوعة. لا تضع بدل التآكل مكان A.',
'guide_radius_b311': 'R هو نصف قطر الانحناء المطلوب في معادلة القطع المتقاربة B31.1-2022 الفقرة 104.2.3(c)(3)(-a). خذ R ونصف قطر الماسورة r من الرسم المعتمد بتعريفات ASME B31J المحال إليها. يحتاج الحساب R > r. لا تضع قطر الماسورة مكان R، ولا تفترض تطابق تعريفه تلقائيًا مع نصف القطر الفعّال في B31.3.',
'guide_miter_spacing': 'حدد متقاربة أو متباعدة من هندسة التجميعة المعتمدة وفق ASME B31J، كما تطلب B31.1-2022 الفقرة 104.2.3(c)(3). يعتمد التطبيق على التصنيف الذي تعلنه، ولا يستنتجه من العدد أو الزاوية وحدهما. المتقاربة تستخدم نسبة أنصاف الأقطار، والمتباعدة تحل المعادلة الضمنية المطبوعة. فحص السمك لا يعوض التأهيل وفق 104.7.',
'guide_miter_tm': 'tm هو أقل جدار مطلوب للماسورة المستقيمة وفق B31.1 الفقرة 104.1 لنفس المادة والضغط والحرارة والسماحيات، بالملليمتر. احسبه أولًا في تبويب سمك الماسورة مع اختيار B31.1، أو خذه من حساب تصميم معتمد. انقل tm شاملًا A، وليس سمك الضغط t وحده ولا الجدار الاسمي المشترى. هو الأساس الذي تُحسب منه سماكة قطعة المايل ts في 104.2.3(c)(3).',
'guide_miter_r': 'r هو نصف قطر الماسورة المحدد لهذا الحساب وفق ASME B31J المحال إليه في B31.1-2022 الفقرة 104.2.3. خذه من الهندسة المعتمدة وتعريف الجدار المنطبق. أدخل ملليمترات لا قطرًا، وميّزه عن نصف قطر انحناء التجميعة R. تحتوي المعادلات r/R أو sqrt(r/ts)؛ وضع القطر بدل نصف القطر يغيّر النتيجة.',
'guide_e_b311': 'E، أو F للمادة المصبوبة، معامل الجودة لشكل المنتج الفعلي من B31.1-2022 الملحق A والفقرة 102.4.3. حدد بدون لحام/ERW/لحام فرن/مسبوك من الشهادة. صف A106 بدون لحام المرفق له E=1، ولا يبرر ذلك 1 لكل الأنابيب. قد تكون قيم الإجهاد في الجدول SE/SF أصلًا؛ أدخل S غير المخفض مع E مرة واحدة فقط.',
'guide_w_b311': 'W معامل تخفيض قوة اللحام بلا وحدة حسب B31.1-2022 الفقرة 102.4.7. حدد انطباقه من المادة ونوع اللحام وحرارة معدن التصميم والجدول والملاحظات المقررة. استخدم الشهادة وأساس التصميم وإصدار الكود المحدد. يختلف عن معامل الجودة E. المجال أكبر من صفر وحتى 1؛ استخدم 1 إذا كان مبررًا، وليس لأنه يعطي جدارًا أرق.',
'guide_y_b311': 'y معامل بلا وحدة من B31.1-2022 جدول 104.1.2-1 للمجموعة والحرارة المختارتين. يستوفي التطبيق خلايا y المنشورة ويطبق الملاحظة (b) للفولاذ المنطبق حتى 482°م وعند Do/tm<6. ليس S ولا يثبت صلاحية المادة للحرارة. الإدخال اليدوي يتجاوز الجدول؛ راجع المصدر والملاحظات قبل التعديل.',
'guide_material_vessel': 'استخدم مواصفة المادة وشكل المنتج من شهادة الوعاء؛ مثل لوح SA-516 بدل درجة ماسورة. القائمة للتعريف فقط. تحقق من سماح استخدام المادة في VIII Division 1 ومن صف الإجهاد وملاحظاته في Section II-D جدول 1A/1B عند حرارة التصميم. استخدم «أخرى» لكتابة التسمية الدقيقة من الشهادة عند الحاجة.',
'guide_generic': 'خذ القيمة أو التسمية من مستند التصميم أو التصنيع المعتمد لهذا البند. أسماء التقارير والمراجع الاختيارية للتعريف ولا تغيّر المعادلة. إذا لم تتوفر قيمة هندسية مطلوبة، احصل عليها من مسؤول التصميم بدل تخمينها.',
'help_material': 'اختر مواصفة ASTM والدرجة وطريقة التصنيع بدقة من شهادة فحص/مادة المصنع MTC. القائمة للتعريف ولا تثبت الصلاحية للخدمة. يعتمد S على الكود وحرارة المعدن، وE على التصنيع، وW على قواعد اللحام والحرارة. اختر «أخرى» لتسمية غير مدرجة، وراجع جدول المادة والملاحظات في الكود.',
'help_material_name': 'انقل المواصفة والدرجة وشكل المنتج ورقم UNS المنطبق من شهادة المادة أو مواصفة الأنابيب المعتمدة. مثال: ASTM A106 Gr.B ماسورة بدون لحام. الاسم التجاري أو «صلب كربوني» وحدهما لا يكفيان لاختيار صف الإجهاد.',
'help_temperature': 'حرارة معدن التصميم بالدرجة المئوية، من Line List أو ورقة بيانات المعدة أو أساس التصميم للحالة الحاكمة للضغط والحرارة. الافتراضي 20°م بداية عند حرارة الغرفة، وليس افتراضًا لحرارة الخدمة. راجع S عند تغيير الحرارة، ولا تستخدم إجهاد حرارة الغرفة لخط ساخن. تغيير المادة أو الحرارة يبطل المعاملات التابعة القديمة.',
'help_od': 'القطر الخارجي D/Do، وليس NPS أو القطر الداخلي. خذه من أبعاد B36.10/B36.19 للمنتج، أو رسم المصنع المعتمد، أو القياس المقبول حيث يسمح الكود. استبعد الطلاء. حقل «مم» يحتاج ملليمترات؛ وفي حقل الوحدة المختارة استخدم تلك الوحدة. مثال: NPS 4 قطره الخارجي 114.3 مم وليس 4 مم.',
'help_pressure': 'ضغط التصميم الداخلي بالنسبة للجو bar(g)، من Line List أو P&ID أو ورقة التصميم المعتمدة. الضغط المقاس بالنسبة للجو يختلف عن المطلق؛ حوّل المطلق بشكل مناسب قبل الإدخال. لا تدخل ضغط الاختبار الهيدروستاتيكي أو قراءة التشغيل إلا إذا كانت حالة التصميم المعتمدة. مثال: 20 bar(g) = 2 MPa، ويحوّل التطبيق الوحدات قبل الحساب.',
'help_corrosion': 'بدل التآكل بالملليمتر للمعدن المتوقع فقده خلال عمر التصميم، من كلاس الأنابيب أو دراسة التآكل أو مواصفة الوعاء المعتمدة. ليس فقد الجدار المقاس في ماسورة قديمة. مثال: بدل 1.5 مم يدخل 1.5. أدخل صفرًا فقط إذا برره أساس التصميم.',
'help_erosion': 'بدل نحر إضافي بالملليمتر من تقييم التصميم/التآكل والنحر للمائع والسرعة والجسيمات. لا تكرر مبلغًا للنحر داخل بدل التآكل بالمواصفة. أدخل صفرًا إذا لم يطلب التصميم سماحية منفصلة للنحر.',
'mechanical_allowance_hint': 'المعدن المزال بالقلاوظ أو المجاري أو التشغيل بالملليمتر، من رسم التصنيع والتفاوت. تطلب B31.3-2018 الفقرة 304.1.1(b) عمق القلاوظ/المجرى؛ وعند عدم تحديد تفاوت التشغيل أو المجرى أضف 0.5 مم إلى عمق القطع المحدد. في B31.1 راجع 102.4.2 وسماحيات القوة الميكانيكية في 102.4.4. تدخل السماحية في الجدار قبل التشغيل؛ لا تخصم المعدن المزال مرة ثانية من قياس نهائي.',
'mill_tolerance_hint': 'تفاوت النقص المسموح للجدار كنسبة مئوية، من مواصفة المنتج والشراء والشهادة المحددة، مثل مواصفة ASTM/ASME المنطبقة. لا تفترض 12.5% لكل المنتجات. سمك الطلب الاسمي = الحد الأدنى المطلوب/(1−tol/100). هذا فحص شراء، وليس خصمًا من أقل جدار مقاس ومعتمد.',
'help_e': 'معامل الجودة E بلا وحدة من B31.3-2018 جدول A-1A/A-1B وملاحظات 302.3.3/302.3.4 لشكل المنتج وفحص اللحام الفعلي. حدد بدون لحام أو ملحوم من MTC، ثم اقرأ الصف المناسب. قد تنطبق 1 لمنتج مناسب بدون لحام، لكنها ليست عامة. استخدم S من A-1/A-1M منفصلًا وطبّق E مرة واحدة؛ ليست W ولا إجهاد الخضوع.',
'help_w': 'W معامل تخفيض قوة وصلة اللحام عند حرارة معدن التصميم، من B31.3-2018 الفقرة 302.3.5(e) وجدول 302.3.5، شاملًا مجموعة الصلب والمعالجة الحرارية والملاحظات. استخدم شهادات المادة واللحام وأساس التصميم. بلا وحدة ويختلف عن E. يجب تأكيد قيمة البدء 1 للمادة واللحام والحرارة الفعلية؛ لا تُبقِ قيمة خدمة باردة عند حرارة عالية دون مراجعة.',
'help_y': 'Y معامل بلا وحدة من B31.3-2018 جدول 304.1.1 حسب عائلة المادة والحرارة، وليس الإجهاد المسموح. انتقال الفيريتي المطبوع 0.4/0.5/0.7 عند 482/510/538°م؛ والأوستنيتي عند 566/593/621°م. القيم التلقائية من الجدول والاستيفاء حيث تتوفر، ويمكنك تعديلها بعد مراجعة الصف والملاحظات. تظل حدود المعادلة المبسطة t<D/6 وP/(SE)≤0.385 مطلوبة.',
'help_bend_radius': 'R1 نصف قطر الانحناء لخط المركز بالملليمتر، من رسم أبعاد الكوع لدى المصنع أو رسم ثني الماسورة؛ وليس نصف قطر مقطع الماسورة. تستخدم B31.3-2018 الفقرة 304.2.1 النسبة R1/D في I. تسمية الكوع القياسي «طويل 1.5D» عادةً مرتبطة بالمقاس الاسمي؛ لا تضرب القطر الخارجي الفعلي في 1.5 تلقائيًا. أدخل نصف القطر المعتمد (مثل نحو 152 مم عادةً لكوع NPS 4 طويل)، ويجب R1>D/2.',
'help_joint_efficiency': 'كفاءة وصلة الوعاء E بلا وحدة من ASME VIII Division 1 جدول UW-12 ومتطلبات الفحص المنطبقة في UW-11. استخدم خريطة لحامات الوعاء وفئة/نوع الوصلة وسجلات التصوير والفحص. لا تستخدم جدول معامل جودة الأنابيب هنا. الافتراضي 1 يحتاج صفًا وفحصًا يبررانه؛ خذ الكفاءة المعتمدة من مصمم الوعاء.',
'help_nominal_vessel_thickness': 'سمك اللوح أو جدار المكوّن الاسمي بالملليمتر من رسم الوعاء أو شهادة اللوح، لفحص MAWP. يستخدم التطبيق السمك ناقص بدل التآكل مع حدود المكوّن المنفذة. لا يتنبأ بترقيق التشكيل ولا يؤهل كل أحمال الوعاء. لا تدخل ناتج سمك الضغط كأنه جدار مقاس أو مشترى.',
}

en.update({'export_miter_report':'Export Miter Report', 'guide_b311_conditions':'Declare only after checking B31.1-2022 104.2.3(a)(2)-(5): each segment meets 104.1 thickness; the fluid is nonflammable, nontoxic and incompressible (gaseous vents excepted); fewer than 7,000 full pressure cycles during service life; and full penetration welds. Find evidence in the design calculations, fluid safety data, operating cycle specification and qualified weld drawings. Unknown means unchecked; this is a declaration, not automatic verification.'})
ar.update({'export_miter_report':'تصدير تقرير الوصلة المقطعية', 'guide_b311_conditions':'لا تؤكد الشرط إلا بعد مراجعة B31.1-2022 الفقرة 104.2.3(a)(2)-(5): سمك كل مقطع يحقق 104.1؛ المائع غير قابل للاشتعال وغير سام وغير قابل للانضغاط مع استثناء التنفيس الغازي؛ أقل من 7000 دورة ضغط كاملة طوال عمر الخدمة؛ ولحامات اختراق كامل. راجع حسابات التصميم وبيانات سلامة المائع ومواصفات دورات التشغيل ورسومات اللحام المؤهلة. عند عدم معرفة الشرط اتركه غير مؤكد؛ هذا إقرار من المستخدم وليس تحققًا آليًا.'})
en.update({
'stress_input_hint':'S must match the selected code, material/product and design metal temperature. Use the stress table in the ? help; room-temperature yield strength does not determine S.',
'help_nps':'NPS is the nominal pipe designation from the line specification, isometric drawing or purchase order, not a measured diameter. The actual OD is loaded from B36.10-2022 (e.g. NPS 4 has OD 114.3 mm). Use Custom and the measured/drawing OD if the size is not listed.',
'help_schedule':'The schedule is a nominal wall designation from the piping specification or pipe marking/purchase certificate. B36.10-2022 supplies the nominal wall for that NPS and schedule. This limited table does not include every schedule. For an unlisted product enter the nominal wall manually; verify finished minimum wall separately.',
'help_density':'Mass density in kg/m³ from the material supplier datasheet or approved material properties. The selected common steel value is an approximate default: 7850 for carbon steel, 8000 for common austenitic stainless steel. Edit for the actual material. Do not enter specific gravity (e.g. 7.85); enter 7850 kg/m³. It affects mass only, never allowable stress.',
'help_length':'Total centreline pipe length in metres, from the cutting list, isometric drawing or measurement. Enter 6 for six metres, not 6000 mm. Pipe mass and water mass scale with length; fittings, coatings and insulation are excluded.',
'help_vessel_radius':'Inside radius in the corroded condition, in mm, from the vessel/head dimensioned drawing: for internal corrosion use the new inside radius plus the internal corrosion allowance. Do not enter OD/2. This is R for a shell, L for a hemisphere, and D/2 for elliptical/conical forms. The wall allowances are added separately.',
'help_vessel_crown':'Inside crown radius L of a torispherical head in mm, from the formed-head supplier drawing, in the corroded condition. It is the large curved crown radius, not the vessel cross-section radius. Blank uses inside diameter; accept that default only if it matches the actual head drawing. Used by UG-32(e)/Appendix 1-4(d).',
'help_vessel_knuckle':'Inside knuckle radius r in mm from the formed-head drawing, in the corroded condition: the tight radius at the crown-to-flange transition. Blank uses r=0.06L for the standard 6% head, reproducing 0.885 in UG-32(e). Other supported geometry uses M=[3+sqrt(L/r)]/4 from Appendix 1-4(d); confirm the actual dimensions.',
'help_vessel_half_apex':'Half-apex angle alpha in degrees from the cone fabrication drawing: the angle between the cone wall and vessel axis, half the full apex angle. Enter degrees, not radians. UG-32(g) covers up to 30 degrees; greater angles need a reinforced-cone design outside this calculator.',
'help_vessel_ellipsoidal_ratio':'D/(2h): inside diameter divided by twice the inside crown depth, measured from the tangent line, excluding the straight flange. Obtain D and h from the formed-head drawing in the corroded condition. Enter 2 for a standard 2:1 head (K=1); the supported range is 1 to 2. The app applies K=[2+(D/2h)^2]/6. Shallower heads need a separate design.'})
ar.update({
'stress_input_hint':'يجب أن تطابق S الكود والمادة وشكل المنتج وحرارة المعدن التصميمية. مرجع جدول الإجهاد في علامة ؟؛ إجهاد الخضوع عند حرارة الغرفة لا يحدد S.',
'help_nps':'NPS هو المقاس الاسمي من مواصفة الخط أو رسم الأيزومتريك أو أمر الشراء، وليس القطر المقاس. يجلب التطبيق القطر الخارجي من B36.10-2022؛ مثلًا NPS 4 قطره الخارجي 114.3 مم. للمقاس غير المدرج اختر مخصص وأدخل القطر من الرسم أو القياس.',
'help_schedule':'رقم Schedule يحدد السمك الاسمي من مواصفة الخط أو وسم الماسورة وشهادة الشراء. يقدم B36.10-2022 سمكًا لكل مقاس وجدول؛ القائمة الحالية محدودة. للمقاس غير المدرج أدخل السمك الاسمي يدويًا، وافحص أقل سمك بعد التصنيع بشكل مستقل.',
'help_density':'كثافة الكتلة بوحدة كجم/م³ من بيانات مصنع المادة أو خواص المادة المعتمدة. القيمة الافتراضية تقريبية: 7850 للفولاذ الكربوني و8000 للستانلس الأوستنيتي الشائع. عدلها للمادة الفعلية. لا تدخل الثقل النوعي 7.85؛ أدخل 7850 كجم/م³. تؤثر على الكتلة فقط ولا تحدد الإجهاد المسموح.',
'help_length':'طول الماسورة الكلي على خط المركز بالمتر، من قائمة القطع أو الأيزومتريك أو القياس. أدخل 6 لستة أمتار، لا 6000 مم. تتناسب كتلة الماسورة والماء مع الطول؛ الحساب يستثني الوصلات والطلاء والعزل.',
'help_vessel_radius':'نصف القطر الداخلي بحالة التآكل بالمليمتر من رسم الوعاء أو الرأس؛ للتآكل الداخلي يساوي نصف القطر الجديد زائد بدل التآكل الداخلي. لا تدخل نصف القطر الخارجي. يمثل R للأسطوانة وL لنصف الكرة وD/2 للرأس الإهليلجي أو المخروطي. تضاف بدلات السمك بشكل منفصل.',
'help_vessel_crown':'نصف قطر التاج الداخلي L للرأس التوريسفيري بالمليمتر من رسم مصنع الرأس المشكل بحالة التآكل. هو نصف قطر انحناء التاج الكبير وليس نصف قطر مقطع الوعاء. تركه فارغًا يستخدم القطر الداخلي؛ لا تعتمد الافتراضي إلا إذا وافق الرسم الفعلي. يستخدم في UG-32(e) والملحق 1-4(d).',
'help_vessel_knuckle':'نصف قطر الركبة الداخلي r بالمليمتر من رسم الرأس المشكل بحالة التآكل؛ هو الانحناء الصغير عند انتقال التاج إلى الحافة. تركه فارغًا يستخدم r=0.06L للرأس القياسي 6% ويحقق معامل 0.885 في UG-32(e). الهندسة الأخرى المدعومة تستخدم M=[3+sqrt(L/r)]/4 من الملحق 1-4(d)؛ راجع الأبعاد الفعلية.',
'help_vessel_half_apex':'نصف زاوية رأس المخروط بالدرجات من رسم التصنيع؛ الزاوية بين جدار المخروط ومحور الوعاء، وتساوي نصف الزاوية الكلية عند القمة. أدخل درجات لا راديان. يغطي UG-32(g) زاوية حتى 30 درجة؛ الأكبر يحتاج تصميم مخروط مقوى خارج نطاق الحاسبة.',
'help_vessel_ellipsoidal_ratio':'D/(2h): القطر الداخلي مقسوم على ضعف عمق التاج الداخلي من خط التماس دون الحافة المستقيمة. احصل على D وh من رسم الرأس بحالة التآكل. أدخل 2 للرأس القياسي 2:1 ومعامله K=1؛ المجال المدعوم 1 إلى 2. يستخدم التطبيق K=[2+(D/2h)^2]/6. الرأس الأكثر تسطحًا يحتاج تصميمًا منفصلًا.'})
en['guide_miter_t_b311']='For B31.1-2022 104.2.3(a)(1)/(b)(2), this field is the nominal segment wall tn in mm from the purchase specification, pipe wall schedule or fabrication drawing. It is compared with crotch dimension B as B<6tn or B>=6tn to choose the pressure path. This does not verify actual remaining wall or prove that every segment meets 104.1; confirm those separately. The optional segment wall calculation below uses straight-pipe minimum tm, not tn.'
ar['guide_miter_t_b311']='في B31.1-2022 الفقرة 104.2.3(a)(1)/(b)(2)، يمثل هذا الحقل السمك الاسمي للمقطع tn بالمليمتر من مواصفة الشراء أو جدول السمك أو رسم التصنيع. يقارن ببعد باطن الوصلة B وفق B<6tn أو B≥6tn لاختيار مسار الضغط. لا يثبت أقل جدار متبقٍ ولا أن كل مقطع يحقق 104.1؛ راجع ذلك مستقلًا. حساب سمك المقطع الاختياري أدناه يستخدم الحد الأدنى للماسورة المستقيمة tm وليس tn.'
en['guide_water_fill']='Enable when you want the mass of water completely filling the pipe bore in addition to bare-pipe mass. The app uses ID=D-2t and water density 1000 kg/m³. This is an estimate for water near room temperature; it is not the mass of steam, oil, another fluid or a partially filled pipe. Get the fill condition and length from the service/test specification.'
ar['guide_water_fill']='فعّله لإضافة كتلة الماء الذي يملأ تجويف الماسورة بالكامل إلى كتلة الماسورة المجردة. يستخدم التطبيق ID=D−2t وكثافة ماء 1000 كجم/م³. هو تقدير للماء قرب حرارة الغرفة، وليس كتلة بخار أو زيت أو مائع آخر أو ملء جزئي. تحقق من حالة الملء والطول من مواصفة التشغيل أو الاختبار.'
en['field_miter_nominal_tn']='Nominal segment wall tn (mm)'
ar['field_miter_nominal_tn']='السمك الاسمي للمقطع tn (مم)'
formats = {'stress_verified_source'}
for folder, values in [('values',en),('values-ar',ar)]:
    path = Path('app/src/main/res')/folder/'strings.xml'
    s = path.read_text(encoding='utf-8')
    for key,value in values.items():
        # Let XML escaping handle comparison operators; escape Android apostrophes.
        value = escape(value).replace("'", "\\'").replace('\n','\\n')
        tag = f'<string name="{key}"'+('' if key in formats else ' formatted="false"')+'>'+value+'</string>'
        pattern = r'<string name="'+re.escape(key)+r'"[^>]*>.*?</string>'
        if re.search(pattern,s,re.S): s = re.sub(pattern,lambda _:tag,s,count=1,flags=re.S)
        else: s = s.replace('</resources>','    '+tag+'\n</resources>')
    path.write_text(s,encoding='utf-8')
